# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 00:48
from __future__ import unicode_literals

import circle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=circle.models.populate_circle_slug, max_length=8)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('image', models.ImageField(upload_to=circle.models.circle_image_upload)),
                ('contributors', models.ManyToManyField(to='contributor.Contributor')),
            ],
        ),
    ]
