# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170812_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='circle',
        ),
        migrations.AddField(
            model_name='submission',
            name='authors',
            field=models.ManyToManyField(related_name='submissions', to='core.Circle'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='publish_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='user',
            name='circles',
            field=models.ManyToManyField(related_name='members', to='core.Circle'),
        ),
    ]
