# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
